Update snyk-security.yml

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -54,7 +54,12 @@ jobs:
         # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
         # Use || true to not fail the pipeline
       - name: Snyk Code test
-        run: snyk code test --sarif > snyk-code.sarif || true
+        run: |
+          snyk code test --sarif > snyk-code.sarif 2> snyk-error.log || true
+          if [ -s snyk-error.log ]; then
+            echo "Snyk code test reported errors:"
+            cat snyk-error.log
+          fi
       
       - name: Snyk Open Source test client
         working-directory: ./client
